export const DELETE_LINK_START = 'DELETE_LINK_START';
export const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS';
export const DELETE_LINK_FAILURE = 'DELETE_LINK_FAILURE';
export const DELETE_LINK_CLEAR = 'DELETE_LINK_CLEAR';
