name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  coverage:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
      # - uses: jpb06/jest-badges-action@latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # branches: master,preprod,staging
          cache: 'yarn'
      - run: yarn test
